In [3]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt

In [21]:
Image_Size = 256
Batch_Size = 32
Channels = 32

In [7]:
dataset = tf.keras.preprocessing.image_dataset_from_directory(
    'PlantVillage', shuffle = True, image_size = (Image_Size, Image_Size), 
    batch_size = Batch_Size
    )

Found 2152 files belonging to 3 classes.


In [17]:
type(dataset)

tensorflow.python.data.ops.dataset_ops.BatchDataset

In [9]:
Class_Names = dataset.class_names
Class_Names

['Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy']

In [13]:
#Batches = 32. Files = 2152. Files/Batches = 67.25
#68 * 32 = 2176
len(dataset)

68

In [19]:
for image_batch, label_batch in dataset.take(1):    #dataset was created as pairs of (image, label)
    print(image_batch.shape)
    print(label_batch.numpy())

(32, 256, 256, 3)
[0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 2 1 2 1 1 0 1 0 0 1 0 0]


In [27]:
print(type(image_batch))
print(type(label_batch))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [29]:
image_batch[0]

<tf.Tensor: shape=(256, 256, 3), dtype=float32, numpy=
array([[[154., 152., 166.],
        [152., 150., 164.],
        [151., 149., 163.],
        ...,
        [140., 139., 153.],
        [140., 139., 153.],
        [137., 136., 150.]],

       [[158., 156., 170.],
        [156., 154., 168.],
        [155., 153., 167.],
        ...,
        [134., 133., 147.],
        [140., 139., 153.],
        [142., 141., 155.]],

       [[162., 160., 174.],
        [160., 158., 172.],
        [159., 157., 171.],
        ...,
        [137., 136., 150.],
        [146., 145., 159.],
        [152., 151., 165.]],

       ...,

       [[186., 183., 192.],
        [184., 181., 190.],
        [180., 177., 186.],
        ...,
        [185., 180., 186.],
        [173., 168., 174.],
        [172., 167., 173.]],

       [[185., 182., 191.],
        [182., 179., 188.],
        [179., 176., 185.],
        ...,
        [168., 163., 169.],
        [160., 155., 161.],
        [162., 157., 163.]],

       [[184., 18

In [39]:
image_batch[0].shape

TensorShape([256, 256, 3])

In [31]:
image_batch[0].numpy()

array([[[154., 152., 166.],
        [152., 150., 164.],
        [151., 149., 163.],
        ...,
        [140., 139., 153.],
        [140., 139., 153.],
        [137., 136., 150.]],

       [[158., 156., 170.],
        [156., 154., 168.],
        [155., 153., 167.],
        ...,
        [134., 133., 147.],
        [140., 139., 153.],
        [142., 141., 155.]],

       [[162., 160., 174.],
        [160., 158., 172.],
        [159., 157., 171.],
        ...,
        [137., 136., 150.],
        [146., 145., 159.],
        [152., 151., 165.]],

       ...,

       [[186., 183., 192.],
        [184., 181., 190.],
        [180., 177., 186.],
        ...,
        [185., 180., 186.],
        [173., 168., 174.],
        [172., 167., 173.]],

       [[185., 182., 191.],
        [182., 179., 188.],
        [179., 176., 185.],
        ...,
        [168., 163., 169.],
        [160., 155., 161.],
        [162., 157., 163.]],

       [[184., 181., 190.],
        [183., 180., 189.],
        [182., 1

In [37]:
image_batch[:2].numpy()    #Notice the increase in dimension

array([[[[154., 152., 166.],
         [152., 150., 164.],
         [151., 149., 163.],
         ...,
         [140., 139., 153.],
         [140., 139., 153.],
         [137., 136., 150.]],

        [[158., 156., 170.],
         [156., 154., 168.],
         [155., 153., 167.],
         ...,
         [134., 133., 147.],
         [140., 139., 153.],
         [142., 141., 155.]],

        [[162., 160., 174.],
         [160., 158., 172.],
         [159., 157., 171.],
         ...,
         [137., 136., 150.],
         [146., 145., 159.],
         [152., 151., 165.]],

        ...,

        [[186., 183., 192.],
         [184., 181., 190.],
         [180., 177., 186.],
         ...,
         [185., 180., 186.],
         [173., 168., 174.],
         [172., 167., 173.]],

        [[185., 182., 191.],
         [182., 179., 188.],
         [179., 176., 185.],
         ...,
         [168., 163., 169.],
         [160., 155., 161.],
         [162., 157., 163.]],

        [[184., 181., 190.],
       